name: 🔷 CENTOS SSH - NGROK

on:
  workflow_dispatch:
    inputs:
      duration:
        description: '🕐 Thời gian sử dụng'
        required: false
        default: '6h'
        type: choice
        options:
        - '1h'
        - '2h'
        - '3h'
        - '4h'
        - '5h'
        - '6h'
      config:
        description: '⚙️ Cấu hình VPS'
        required: false
        default: 'basic'
        type: choice
        options:
        - 'basic'
        - 'standard'
        - 'premium'

jobs:
  CentOS-SSH-Ngrok:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
      - name: 🎯 KHỞI ĐỘNG HỆ THỐNG
        run: |
          echo "🔷 CENTOS SSH SERVER - NGROK"
          echo "⚡ Public Access via Ngrok"
          echo "🕒 Thời gian: ${{ github.event.inputs.duration }}"

      - name: 🔧 CẤU HÌNH SSH
        run: |
          echo "🛠️ ĐANG CẤU HÌNH SSH"
          sudo apt-get update -qq
          sudo apt-get install -y openssh-server curl
          sudo sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh
          echo "✅ SSH Server đã sẵn sàng"

      - name: 👤 TẠO TÀI KHOẢN
        run: |
          echo "👤 ĐANG TẠO TÀI KHOẢN"
          PASSWORD=$(openssl rand -base64 12 | tr -dc 'A-Za-z0-9' | head -c 10)
          sudo useradd -m -s /bin/bash aistv-ngrok
          echo "aistv-ngrok:$PASSWORD" | sudo chpasswd
          sudo usermod -aG sudo aistv-ngrok
          echo "aistv-ngrok ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/aistv-ngrok
          echo "$PASSWORD" > /tmp/ssh_password.txt
          echo "✅ Tài khoản sẵn sàng"

      - name: 🌐 THIẾT LẬP NGROK
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          echo "🌐 ĐANG THIẾT LẬP NGROK"
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt-get update && sudo apt-get install -y ngrok
          ngrok authtoken $NGROK_AUTH_TOKEN
          ngrok tcp 22 --log=stdout > /tmp/ngrok.log 2>&1 &
          sleep 10
          NGROK_URL=$(curl -s http://localhost:4040/api/tunnels | grep -oP '"public_url":"tcp://\K[^"]+' | head -1)
          echo "NGROK_URL=$NGROK_URL" >> $GITHUB_ENV
          echo "✅ Ngrok URL: $NGROK_URL"

      - name: 📤 GỬI THÔNG TIN
        run: |
          PASSWORD=$(cat /tmp/ssh_password.txt)
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          curl -X POST "https://wxqxriwodkgzpzqaxigp.supabase.co/functions/v1/update-rdp-info" \
            -H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4cXhyaXdvZGtnenB6cWF4aWdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM4Nzk0MDcsImV4cCI6MjA3OTQ1NTQwN30.u8piIXHELUvdN9klNTFhnBFrD0lzwMg0EMPcrz1Wfh8" \
            -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4cXhyaXdvZGtnenB6cWF4aWdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM4Nzk0MDcsImV4cCI6MjA3OTQ1NTQwN30.u8piIXHELUvdN9klNTFhnBFrD0lzwMg0EMPcrz1Wfh8" \
            -H "Content-Type: application/json" \
            -d "{\"repoName\":\"$REPO_NAME\",\"ngrokUrl\":\"$NGROK_URL\",\"rdpUser\":\"aistv-ngrok\",\"rdpPassword\":\"$PASSWORD\",\"osType\":\"centos\"}" \
            || echo "⚠️ Warning"

      - name: ⏳ DUY TRÌ PHIÊN
        run: |
          DURATION="${{ github.event.inputs.duration }}"
          HOURS=${DURATION%h}
          MINUTES=$((HOURS * 60))
          echo "🔄 Duy trì $HOURS giờ..."
          for ((i=MINUTES; i>0; i--)); do
            echo -ne "\r⏱️ Còn: $((i/60))h $((i%60))m   "
            sleep 60
          done
